name: Build iOS App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unzip source project
        run: |
          unzip source.zip

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build App for REAL iOS Device (arm64)
        run: |
          xcodebuild build \
            -project VTFViewerIOS.xcodeproj \
            -scheme VTFViewerIOS \
            -destination 'generic/platform=iOS' \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            IPHONEOS_DEPLOYMENT_TARGET=15.0

      - name: Package to IPA
        run: |
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/VTFViewerIOS.app Payload/
          zip -r VTFViewerIOS.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VTFViewerIOS-IPA
          path: VTFViewerIOS.ipa
